<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Biller extends CI_Controller {

    function __construct() {
        parent::__construct();
        $this->load->helper(array('form', 'url'));
        $this->load->model('login_model');
        $this->load->library('form_validation');
        $this->load->library('session');
        $this->load->library('email');
        define('company_logo', base_url('uploads/biller_company_logo/'));
		 define('bill_invoice', base_url('uploads/invoice/'));
		 $path='/var/www/uploads/invoice/';
        if ($this->session->userdata('biller_id') == FALSE) {
            redirect('biller_login');
        }else{
        	$biller_id= $this->session->userdata('biller_id');
        }
    }

    function index() {
    	$where=array('biller_id'=>$this->session->userdata('biller_id'));
		$data['biller_details'] = $this->login_model->get_data_where_condition('biller_details', $where);
		$this->load->view('biller/menu');
        $this->load->view('biller/header');
        $this->load->view('biller/home',$data);
        $this->load->view('biller/footer');
		
    }
	// biller consumer list///
	function consumer_list()
	{
		$where=array('biller_id'=>$this->session->userdata('biller_id'));
		$data['biller_details'] = $this->login_model->get_data_where_condition('biller_user', $where);
		//$data['biller_details'] = $this->login_model->get_record('biller_user');
		$this->load->view('biller/menu');
        $this->load->view('biller/header');
        $this->load->view('biller/listing/biller_user_view', $data);
        $this->load->view('biller/footer');
	}
	function pdf(){
		$this->load->library('PDF');
       
        $pdf = new PDF();
        // Data loading
        $pdf->AddPage();
			$where=array('biller_customer_id_no'=>'9110036985');
			$data= $this->login_model->get_join_three_table_where('biller_details','biller_user','biller_category','biller_id','biller_id','biller_category_id','biller_category_id',$where);
		//	print_r($data['rec']);
			 $data['image']=company_logo; 
		// $data= $this->login_model->get_record_join_two_table('biller_user','biller_details','biller_id','biller_id','',$where);
     //  $where=array('biller_id'=>$this->session->userdata('biller_id'));
		//$data = $this->login_model->get_data_where_condition('biller_user', $where);
            $pdf->SignUp($data);
        $pdf->Output();
        //$pdf->Output('/var/www/uploads/'.'Bill'.'.pdf','F');
	}
// add biller user////
 function add_biller_user(){
	 if ($this->input->post('submit')) {
	 	
            $data = $this->input->post();echo $bill_desc=$data['bill_description']; 
            unset($data['submit']);
			$ch = array("biller_customer_id_no" => strtoupper($this->input->post("biller_customer_id_no")), 'biller_id ='=>$this->session->userdata('biller_id'));
            $rec = $this->login_model->get_data_where_condition('biller_user', $ch);
			 if (empty($rec)) {
               $data['biller_id']=$this->session->userdata('biller_id');
			$timestamp = strtotime($data['bill_due_date']);
			$data['bill_due_date']=	 date("Y-m-d", $timestamp);
			$data['bill_invoice_date']=date("Y-m-d");
			 $this->login_model->insert_data('biller_user', $data);
            $this->session->set_flashdata('status', 'Consumer add successfully');
			$this->load->library('PDF');
	       	$pdf = new PDF();
        // Data loading
        $pdf->AddPage();
		$consumer_no=$this->input->post("biller_customer_id_no");
			$where=array('biller_customer_id_no'=>$this->input->post("biller_customer_id_no"));
			$data= $this->login_model->get_join_three_table_where('biller_details','biller_user','biller_category','biller_id','biller_id','biller_category_id','biller_category_id',$where);
			 $data['image']=company_logo; 
			$pdf->SignUp($data);
			$amt=$this->input->post("bill_amount");
        	$invoice_no= strtotime("now").mt_rand(10000000, 99999999);
			
        	$pdf->Output('/var/www/uploads/invoice'.'/'.$consumer_no.'.pdf','F');
         	$data12['bill_invoice']=$consumer_no.'.pdf';
			 $this->login_model->update_data('biller_user', $data12, $where);
			 $bill='././uploads/invoice/'.$consumer_no.'.pdf';
			 $biller_name=$data[0]->biller_company_name;
			 $message='Your Invoice INV#'.$invoice_no.' '.'of amount Naira'.' '.$amt.' '.' is generated by.'.' '.$biller_name.',Kindly make a payment via Recharge';
			 $this->load->library('email');
             $this->email->from('blm.ypsilon@gmail.com', 'Recharge');
                        $this->email->to($this->input->post("biller_user_email")); // $cc_admin_email
                        $this->email->subject('Pay Bill');
                        $this->email->message($message);
                        $this->email->attach($bill);
                        $this->email->send();
			
             } else {
                $this->session->set_flashdata('error', 'Consumer Number bill already genrated');
            }
			
             
            redirect('biller/consumer_list');
        } else {
            
            $this->load->view('biller/menu');
            $this->load->view('biller/header');
            $this->load->view('biller/add/add_bill_user');
            $this->load->view('biller/footer');
        }
}
// edit bill user 
function edit_bill_user() {
        if ($this->input->post('submit')) {
            $data = $this->input->post();
            $where = array('recharge_category_id' => $this->input->post('recharge_category_id'));
            unset($data['recharge_category_id']);
            unset($data['submit']);
            $operator_id = $this->input->post('recharge_category_id');
            $name = $this->input->post('category_name');
            $where = array('recharge_category_id' => $operator_id);

            $data1 = array('category_name' => strtoupper($name), 'recharge_category_id !=' => $operator_id);
            $rec = $this->login_model->get_data_where_condition('recharge_category', $data1);
            if (empty($rec)) {
                unset($data['recharge_category_id']);
                unset($data['submit']);
                $this->login_model->update_data('recharge_category', $data, $where);
                $this->session->set_flashdata('status', 'Recharge Category Update successfully');
             } else {
                $this->session->set_flashdata('error', 'Recharge Category already exist');
            }

            redirect('admin/recharge_category_list');
        } else {
            $category_id = $this->uri->segment(3);
            if (!empty($category_id)) {

                $where = array('recharge_category_id' => $category_id);
                $data['recharge_category'] = $this->login_model->get_data_where_condition('recharge_category', $where);
                $this->load->view('admin/menu');
                $this->load->view('admin/header');
                $this->load->view('admin/add/add_recharge_category', $data);
                $this->load->view('admin/footer');
            } else {
                redirect('admin/recharge_category_list');
            }
        }
    }
    function logout() {
        $this->session->sess_destroy();
        redirect('biller_login');
    }
	    function delete() {
        $delete_type = $this->uri->segment(3);
        $delete_table = $this->uri->segment(4);
        $delete_where_name = $this->uri->segment(5);
        $delete_where_id = $this->uri->segment(6);
		$delete_where = array($delete_where_name => $delete_where_id);
        $delete = $this->login_model->delete_record($delete_table, $delete_where);
        if ($delete == TRUE) {
            if ($delete_type == 'delete_bill_user') {
                $message = 'Bill user deleted successfully!!';
                $this->session->set_flashdata('error', $message);
                redirect('biller/consumer_list');
            }
           
        } else {
            redirect();
        }
    }


	}