<?php
	#AUTOGENERATED BY HYBRIDAUTH 2.1.2 INSTALLER - Wednesday 12th of March 2014 01:44:19 PM

/*!
* HybridAuth
* http://hybridauth.sourceforge.net | http://github.com/hybridauth/hybridauth
* (c) 2009-2012, HybridAuth authors | http://hybridauth.sourceforge.net/licenses.html
*/

// ----------------------------------------------------------------------------------------
//	HybridAuth Config file: http://hybridauth.sourceforge.net/userguide/Configuration.html
// ----------------------------------------------------------------------------------------

return 
	array(
		"base_url" =>  "https://oyacharge.com/hybridauth_lib/hybridauth/", 

		"providers" => array ( 
			// openid providers
			"OpenID" => array (
				"enabled" => true
			),

			"AOL"  => array ( 
				"enabled" => true 
			),

			"Yahoo" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" )
			),

			"Google" => array ( 
				"enabled" => true,
"keys"    => array ("id" => "553803506952-s77tidijflbnuraj5cpf82655hsk01ml.apps.googleusercontent.com","secret" =>"hCIROaKPdOicgHWjsLoHtRK4")
			),

			"Facebook" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "1016269205069240", "secret" =>"72ad1460ad04c59aeddedb5fce45bf50")
			),
			"Twitter" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" =>"MpFL6s2yrU5v2tQZoa8yc4Cng", "secret" =>"vNftUh7TbTcNIZAYb1PGXoz5Fdta2ZjLqruQRqoSqXJdyDZWWB" ) 
			),

			// windows live
			"Live" => array ( 
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),

			"MySpace" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" => "", "secret" => "" ) 
			),

			"LinkedIn" => array ( 
				"enabled" => true,
				"keys"    => array ( "key" =>"75vqpbz9cn0ka8", "secret" =>"lJBTJF2ZZRgIGQYP" ) 
			),

			"Foursquare" => array (
				"enabled" => true,
				"keys"    => array ( "id" => "", "secret" => "" ) 
			),
		),

		// if you want to enable logging, set 'debug_mode' to true  then provide a writable file by the web server on "debug_file"
		"debug_mode" => false,

		"debug_file" => ""
	);
